name: flicker_news_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.4.2+1
  cached_network_image: ^3.3.1
  webview_flutter: ^4.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.11


dev_dependencies:
  flutter_test:
    sdk: flutter





flutter_native_splash:
  color: "#FFEFE8"
  image: assets/splash_photo.png
  android_12:
    image: assets/splash_photo.png
    color: "#FFEFE8"





flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/


  fonts:
    - family: LuckiestGuy
      fonts:
        - asset: fonts/LuckiestGuy-Regular.ttf
    - family: Ojuju
      fonts:
        - asset: fonts/Ojuju-VariableFont_wght.ttf